window.rbdConfig = { loadSettings: () => { const savedData = localStorage.getItem('rbd_app_data'); if (savedData) { const fullData = JSON.parse(savedData); const data = fullData.settings; if (data.phone) { document.querySelectorAll('a[href^="tel:"]:not(.float-btn), .header-top span, .footer-contact').forEach(el => { if (el.tagName === 'A') el.href = `tel:${data.phone}`; el.innerText = el.innerText.includes('CALL') ? `CALL: ${data.phone}` : data.phone; }); } if (data.email) { document.querySelectorAll('a[href^="mailto:"], .footer-email').forEach(el => { el.href = `mailto:${data.email}`; if (!el.querySelector('i')) el.innerText = data.email; }); } if (data.ga && !window.ga_script_loaded) { const script = document.createElement('script'); script.async = true; script.src = `https://www.googletagmanager.com/gtag/js?id=${data.ga}`; document.head.appendChild(script); window.dataLayer = window.dataLayer || []; function gtag() { dataLayer.push(arguments); } gtag('js', new Date()); gtag('config', data.ga); window.ga_script_loaded = true; } } }, captureLead: (formData) => { const savedData = localStorage.getItem('rbd_app_data') || '{"leads":[]}'; const data = JSON.parse(savedData); if (!data.leads) data.leads = []; data.leads.unshift({ id: Date.now(), name: formData.name, phone: formData.phone || '', email: formData.email || '', location: formData.location || 'Unknown', source: formData.source || 'Website Form', type: formData.type || 'Inquiry', service: formData.service || 'General', notes: formData.notes || '', status: 'new', date: new Date().toLocaleDateString() }); localStorage.setItem('rbd_app_data', JSON.stringify(data)); } };
document.addEventListener('DOMContentLoaded', () => {
  window.rbdConfig.loadSettings();
  const windowWidth = window.innerWidth;
  const dropdowns = document.querySelectorAll('.dropdown');
  dropdowns.forEach(dropdown => { const link = dropdown.querySelector('.nav-link'); if (link && windowWidth < 992) { link.addEventListener('click', (e) => { e.preventDefault(); e.stopPropagation(); dropdown.classList.toggle('active'); dropdowns.forEach(other => { if (other !== dropdown) other.classList.remove('active'); }); }); } });
  const navToggle = document.getElementById('nav-toggle');
  const navEl = document.getElementById('site-nav');
  if (navToggle && navEl) { navToggle.addEventListener('click', (e) => { e.stopPropagation(); navEl.classList.toggle('active'); const icon = navToggle.querySelector('i'); if (icon) { icon.classList.toggle('fa-bars'); icon.classList.toggle('fa-times'); } }); navEl.querySelectorAll('a').forEach(link => { link.addEventListener('click', () => { navEl.classList.remove('active'); const icon = navToggle.querySelector('i'); if (icon) { icon.classList.add('fa-bars'); icon.classList.remove('fa-times'); } }); }); document.addEventListener('click', (e) => { if (navEl.classList.contains('active') && !navEl.contains(e.target) && !navToggle.contains(e.target)) { navEl.classList.remove('active'); const icon = navToggle.querySelector('i'); if (icon) { icon.classList.add('fa-bars'); icon.classList.remove('fa-times'); } } }); }
  const lines = ["We Design, Build & Innovate", "Crafting Digital Success Stories", "Turning Ideas Into Reality"]; let li = 0, ci = 0; const typed = document.getElementById('typed-line') || document.querySelector('.hero-title span'); const cursor = document.querySelector('.cursor'); const typingSpeed = 80, erasingSpeed = 40, pause = 1400; if (typed) { function type() { const line = lines[li]; if (ci < line.length) { typed.textContent = line.slice(0, ci + 1); ci++; setTimeout(type, typingSpeed); } else { setTimeout(erase, pause); } } function erase() { if (ci > 0) { typed.textContent = typed.textContent.slice(0, ci - 1); ci--; setTimeout(erase, erasingSpeed); } else { li = (li + 1) % lines.length; setTimeout(type, 350); } } setTimeout(type, 100); } setInterval(() => { if (cursor) cursor.style.opacity = cursor.style.opacity === '0' ? '1' : '0' }, 500);
  document.querySelectorAll('.card').forEach(card => { card.addEventListener('click', () => { const images = card.querySelector('.card-images'); if (images) { if (images.style.display === 'none' || images.style.display === '') { images.style.display = 'grid'; images.scrollIntoView({ behavior: "smooth", block: "start" }); } else { images.style.display = 'none'; } } }); });
  const getQuoteBtn = document.getElementById("get-quote-btn"); const successSection = document.getElementById("success-message"); if (getQuoteBtn && successSection) { getQuoteBtn.addEventListener("click", function (e) { e.preventDefault(); successSection.style.display = "block"; successSection.scrollIntoView({ behavior: "smooth" }); if (window.gsap) gsap.fromTo(".success-inner", { opacity: 0, y: 40 }, { opacity: 1, y: 0, duration: 1, ease: "power3.out" }); }); }
  const filterBtns = document.querySelectorAll('.filter-btn'); const portfolioItems = document.querySelectorAll('.portfolio-item'); if (filterBtns.length > 0) { filterBtns.forEach(btn => { btn.addEventListener('click', () => { filterBtns.forEach(b => b.classList.remove('active')); btn.classList.add('active'); const filterValue = btn.getAttribute('data-filter'); portfolioItems.forEach(item => { const category = item.getAttribute('data-category'); if (filterValue === 'all' || category === filterValue) { item.style.display = ''; item.style.opacity = '0'; setTimeout(() => item.style.opacity = '1', 50); } else { item.style.display = 'none'; } }); }); }); }
  const lightbox = document.getElementById('lightbox'); const lightboxImg = document.getElementById('lightbox-img'); const lightboxCaption = document.getElementById('lightbox-caption'); const closeBtn = document.querySelector('.lightbox-close'); const prevBtn = document.querySelector('.lightbox-prev'); const nextBtn = document.querySelector('.lightbox-next'); let portIndex = 0; function showPortImage(index) { if (index < 0) index = portfolioItems.length - 1; if (index >= portfolioItems.length) index = 0; portIndex = index; const item = portfolioItems[index]; const img = item.querySelector('img'); const title = item.querySelector('h3').textContent; const category = item.querySelector('p').textContent; lightboxImg.src = img.src; if (lightboxCaption) lightboxCaption.textContent = `${title} - ${category}`; } if (lightbox && portfolioItems.length > 0) { portfolioItems.forEach((item, index) => { const btn = item.querySelector('.btn'); if (btn) { btn.addEventListener('click', e => { e.preventDefault(); showPortImage(index); lightbox.style.display = 'block'; document.body.style.overflow = 'hidden'; }); } }); if (prevBtn) prevBtn.addEventListener('click', () => showPortImage(portIndex - 1)); if (nextBtn) nextBtn.addEventListener('click', () => showPortImage(portIndex + 1)); if (closeBtn) closeBtn.addEventListener('click', () => { lightbox.style.display = 'none'; document.body.style.overflow = 'auto'; }); lightbox.addEventListener('click', e => { if (e.target === lightbox) { lightbox.style.display = 'none'; document.body.style.overflow = 'auto'; } }); }
  const contactForm = document.getElementById('contact-form'); if (contactForm) { contactForm.addEventListener('submit', e => { e.preventDefault(); const n = document.getElementById('name').value, em = document.getElementById('email').value, s = document.getElementById('subject').value, m = document.getElementById('message').value; if (window.rbdConfig) window.rbdConfig.captureLead({ name: n, email: em, type: 'Website Lead', service: s }); window.location.href = `mailto:rapidbasedesign1@gmail.com?subject=${encodeURIComponent(s)}&body=Name:${n}%0D%0AEmail:${em}%0D%0A%0D%0AMessage:${m}`; }); }
  const faqHeaders = document.querySelectorAll('.faq-header'); if (faqHeaders.length > 0) { faqHeaders.forEach(header => { header.addEventListener('click', () => { header.parentElement.classList.toggle('active'); }); }); }
});
window.addEventListener('load', () => { const heroVideo = document.querySelector(".hero-video"); if (heroVideo) { heroVideo.muted = true; heroVideo.setAttribute("playsinline", ""); heroVideo.play().catch(() => { }); } if (typeof gsap !== 'undefined' && typeof ScrollTrigger !== 'undefined') { gsap.registerPlugin(ScrollTrigger); gsap.utils.toArray('.section').forEach(sec => { const elements = sec.querySelectorAll('.overlay-glass, .card, .card img, .testimonials-wrap, .list'); if (elements.length > 0) { gsap.from(elements, { scrollTrigger: { trigger: sec, start: 'top 85%' }, y: 60, opacity: 0, stagger: 0.2, duration: 1, ease: 'power4.out' }); } }); gsap.from('.service-card', { scrollTrigger: { trigger: '#services', start: 'top 85%' }, y: 40, opacity: 0, stagger: 0.1, duration: 0.6, ease: 'power2.out' }); } });
window.addEventListener('scroll', () => { const bg = document.querySelector('.parallax-bg'); if (bg) bg.style.transform = 'translateY(' + (window.pageYOffset * 0.3) + 'px)'; });
